In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/raw/delivery_data.csv")

print(df.shape)

(144867, 24)

In [3]:
df.columns.tolist()

['data',
 'trip_creation_time',
 'route_schedule_uuid',
 'route_type',
 'trip_uuid',
 'source_center',
 'source_name',
 'destination_center',
 'destination_name',
 'od_start_time',
 'od_end_time',
 'start_scan_to_end_scan',
 'is_cutoff',
 'cutoff_factor',
 'cutoff_timestamp',
 'actual_distance_to_destination',
 'actual_time',
 'osrm_time',
 'osrm_distance',
 'factor',
 'segment_actual_time',
 'segment_osrm_time',
 'segment_osrm_distance',
 'segment_factor']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 144867 entries, 0 to 144866
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   data                            144867 non-null  str
 1   trip_creation_time              144867 non-null  str
 2   route_schedule_uuid             144867 non-null  str
 3   route_type                      144867 non-null  str
 4   trip_uuid                       144867 non-null  str
 5   source_center                   144867 non-null  str
 6   source_name                     144574 non-null  str
 7   destination_center              144867 non-null  str
 8   destination_name                144606 non-null  str
 9   od_start_time                   144867 non-null  str
 10  od_end_time                     144867 non-null  str
 11  start_scan_to_end_scan          144867 non-null  float64
 12  is_cutoff                       144867 non-null  bool
 13  cutoff_factor                   144867 non-null  int64
 14  cutoff_timestamp                144867 non-null  str
 15  actual_distance_to_destination  144867 non-null  float64
 16  actual_time                     144867 non-null  float64
 17  osrm_time                       144867 non-null  float64
 18  osrm_distance                   144867 non-null  float64
 19  factor                          144867 non-null  float64
 20  segment_actual_time             144867 non-null  float64
 21  segment_osrm_time               144867 non-null  float64
 22  segment_osrm_distance           144867 non-null  float64
 23  segment_factor                  144867 non-null  float64
dtypes: bool(1), float64(10), int64(1), str(12)
memory usage: 25.6 MB

In [5]:
df.isnull().sum().sort_values(ascending=False)

source_name                       293
destination_name                  261
route_schedule_uuid                 0
data                                0
route_type                          0
trip_uuid                           0
source_center                       0
trip_creation_time                  0
destination_center                  0
od_start_time                       0
od_end_time                         0
start_scan_to_end_scan              0
is_cutoff                           0
cutoff_factor                       0
cutoff_timestamp                    0
actual_distance_to_destination      0
actual_time                         0
osrm_time                           0
osrm_distance                       0
factor                              0
segment_actual_time                 0
segment_osrm_time                   0
segment_osrm_distance               0
segment_factor                      0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
print("Unique Trips:", df["trip_uuid"].nunique())

print(
    "Average Rows Per Trip:",
    round(len(df) / df["trip_uuid"].nunique(), 2)
)

Unique Trips: 14817
Average Rows Per Trip: 9.78

In [8]:
df.describe()

,start_scan_to_end_scan,cutoff_factor,actual_distance_to_destination,actual_time,osrm_time,osrm_distance,factor,segment_actual_time,segment_osrm_time,segment_osrm_distance,segment_factor
count,144867.000000,144867.000000,144867.000000,144867.000000,144867.000000,144867.000000,144867.000000,144867.000000,144867.000000,144867.00000,144867.000000
mean,961.262986,232.926567,234.073372,416.927527,213.868272,284.771297,2.120107,36.196111,18.507548,22.82902,2.218368
std,1037.012769,344.755577,344.990009,598.103621,308.011085,421.119294,1.715421,53.571158,14.775960,17.86066,4.847530
min,20.000000,9.000000,9.000045,9.000000,6.000000,9.008200,0.144000,-244.000000,0.000000,0.00000,-23.444444
25%,161.000000,22.000000,23.355874,51.000000,27.000000,29.914700,1.604264,20.000000,11.000000,12.07010,1.347826
50%,449.000000,66.000000,66.126571,132.000000,64.000000,78.525800,1.857143,29.000000,17.000000,23.51300,1.684211
75%,1634.000000,286.000000,286.708875,513.000000,257.000000,343.193250,2.213483,40.000000,22.000000,27.81325,2.250000
max,7898.000000,1927.000000,1927.447705,4532.000000,1686.000000,2326.199100,77.387097,3051.000000,1611.000000,2191.40370,574.250000

In [9]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
start_scan_to_end_scan,144867.0,961.262986,1037.012769,20.000000,161.000000,449.000000,1634.000000,7898.000000
cutoff_factor,144867.0,232.926567,344.755577,9.000000,22.000000,66.000000,286.000000,1927.000000
actual_distance_to_destination,144867.0,234.073372,344.990009,9.000045,23.355874,66.126571,286.708875,1927.447705
actual_time,144867.0,416.927527,598.103621,9.000000,51.000000,132.000000,513.000000,4532.000000
osrm_time,144867.0,213.868272,308.011085,6.000000,27.000000,64.000000,257.000000,1686.000000
osrm_distance,144867.0,284.771297,421.119294,9.008200,29.914700,78.525800,343.193250,2326.199100
factor,144867.0,2.120107,1.715421,0.144000,1.604264,1.857143,2.213483,77.387097
segment_actual_time,144867.0,36.196111,53.571158,-244.000000,20.000000,29.000000,40.000000,3051.000000
segment_osrm_time,144867.0,18.507548,14.775960,0.000000,11.000000,17.000000,22.000000,1611.000000
segment_osrm_distance,144867.0,22.829020,17.860660,0.000000,12.070100,23.513000,27.813250,2191.403700
segment_factor,144867.0,2.218368,4.847530,-23.444444,1.347826,1.684211,2.250000,574.250000

## Data Quality Findings

### Issues Detected

1. Negative values in segment_actual_time
2. Negative values in segment_factor
3. Zero values in segment_osrm_time
4. Extreme outliers in delivery duration columns

### Observations

OSRM travel time systematically underestimates actual travel time.

Median delay factor ≈ 1.86x.

In [10]:
(df["segment_actual_time"] < 0).sum()

np.int64(21)

In [11]:
(df["segment_osrm_time"] == 0).sum()

np.int64(2347)

In [12]:
(df["segment_factor"] < 0).sum()

np.int64(2365)

In [13]:
df = df[df["segment_actual_time"] >= 0]

In [15]:
time_cols = [
    "trip_creation_time",
    "od_start_time",
    "od_end_time",
    "cutoff_timestamp"
]

for col in time_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce", format="mixed")

df[time_cols].head()

,trip_creation_time,od_start_time,od_end_time,cutoff_timestamp
0,2018-09-20 02:35:36.476840,2018-09-20 03:21:32.418600,2018-09-20 04:47:45.236797,2018-09-20 04:27:55.000000
1,2018-09-20 02:35:36.476840,2018-09-20 03:21:32.418600,2018-09-20 04:47:45.236797,2018-09-20 04:17:55.000000
2,2018-09-20 02:35:36.476840,2018-09-20 03:21:32.418600,2018-09-20 04:47:45.236797,2018-09-20 04:01:19.505586
3,2018-09-20 02:35:36.476840,2018-09-20 03:21:32.418600,2018-09-20 04:47:45.236797,2018-09-20 03:39:57.000000
4,2018-09-20 02:35:36.476840,2018-09-20 03:21:32.418600,2018-09-20 04:47:45.236797,2018-09-20 03:33:55.000000

In [16]:
df[time_cols].isna().sum()

trip_creation_time    0
od_start_time         0
od_end_time           0
cutoff_timestamp      0
dtype: int64

In [18]:
df["trip_hour"] = df["trip_creation_time"].dt.hour
df["trip_dayofweek"] = df["trip_creation_time"].dt.dayofweek
df["trip_month"] = df["trip_creation_time"].dt.month
df["trip_weekend"] = (df["trip_dayofweek"] >= 5).astype(int)

df[[
    "trip_hour",
    "trip_dayofweek",
    "trip_month",
    "trip_weekend"
]].head()

   trip_hour  trip_dayofweek  trip_month  trip_weekend
0          2               3           9             0
1          2               3           9             0
2          2               3           9             0
3          2               3           9             0
4          2               3           9             0

In [19]:
df["corridor"] = (
    df["source_center"].astype(str)
    + "->"
    + df["destination_center"].astype(str)
)

df["corridor"].head()

0    IND388121AAA->IND388620AAB
1    IND388121AAA->IND388620AAB
2    IND388121AAA->IND388620AAB
3    IND388121AAA->IND388620AAB
4    IND388121AAA->IND388620AAB
Name: corridor, dtype: str

In [20]:
print("Unique Source Centers:", df["source_center"].nunique())
print("Unique Destination Centers:", df["destination_center"].nunique())

Unique Source Centers: 1508
Unique Destination Centers: 1481

In [21]:
all_centers = set(df["source_center"]) | set(df["destination_center"])
print("Total Unique Centers:", len(all_centers))

Total Unique Centers: 1657

In [22]:
print("Unique Corridors:", df["corridor"].nunique())

Unique Corridors: 2783

In [23]:
df["route_type"].value_counts()

route_type
FTL        99648
Carting    45198
Name: count, dtype: int64

In [24]:
df[df["segment_osrm_time"] == 0][[
    "trip_uuid",
    "source_center",
    "destination_center",
    "segment_actual_time",
    "segment_osrm_time",
    "segment_osrm_distance",
    "segment_factor"
]].head(20)

,trip_uuid,source_center,destination_center,segment_actual_time,segment_osrm_time,segment_osrm_distance,segment_factor
47,trip-153671602871109556,IND362001AAA,IND362220AAA,2.0,0.0,1.2782,-1.0
54,trip-153671602871109556,IND362720AAA,IND362560AAA,0.0,0.0,0.0000,-1.0
90,trip-153816910069311424,IND122004AAA,IND122413AAE,2.0,0.0,0.5277,-1.0
164,trip-153705589682687518,IND206001AAA,IND000000ACB,0.0,0.0,0.0000,-1.0
224,trip-153781356401330282,IND560048AAB,IND560099AAB,0.0,0.0,0.0000,-1.0
236,trip-153746616495500586,IND127201AAA,IND124141AAA,1.0,0.0,1.1662,-1.0
261,trip-153689604975253520,IND560099AAB,IND560058AAB,0.0,0.0,0.0000,-1.0
281,trip-153860909786408355,IND384205AAA,IND384170AAA,0.0,0.0,0.0000,-1.0
298,trip-153807462781768214,IND683511AAA,IND000000ABA,0.0,0.0,0.4861,-1.0
325,trip-153775782037183132,IND413002AAA,IND501359AAE,2.0,0.0,0.4280,-1.0
450,trip-153790475017661884,IND400072AAB,IND421302AAG,0.0,0.0,0.0000,-1.0
465,trip-153674022097541190,IND400072AAB,IND421302AAG,0.0,0.0,0.0000,-1.0
617,trip-153714252401491359,IND781005AAA,IND781018AAB,0.0,0.0,0.0000,-1.0
824,trip-153740455519678193,IND624202AAA,IND625218AAA,0.0,0.0,0.0000,-1.0
827,trip-153801648339170824,IND605601AAA,IND607106AAA,0.0,0.0,0.0000,-1.0
850,trip-153801648339170824,IND606201AAC,IND605601AAA,0.0,0.0,0.0000,-1.0
954,trip-153789659881314008,IND400705AAA,IND421302AAH,0.0,0.0,0.0000,-1.0
972,trip-153721883745449045,IND571104AAA,IND577598AAB,0.0,0.0,0.0000,-1.0
1015,trip-153791084714708100,IND742223AAA,IND742226AAA,8.0,0.0,0.2113,-1.0
1047,trip-153857657012488227,IND591123AAC,IND587103AAB,3.0,0.0,0.1494,-1.0

In [25]:
df[df["segment_factor"] < 0][[
    "trip_uuid",
    "source_center",
    "destination_center",
    "segment_actual_time",
    "segment_osrm_time",
    "segment_osrm_distance",
    "segment_factor"
]].head(20)

,trip_uuid,source_center,destination_center,segment_actual_time,segment_osrm_time,segment_osrm_distance,segment_factor
47,trip-153671602871109556,IND362001AAA,IND362220AAA,2.0,0.0,1.2782,-1.0
54,trip-153671602871109556,IND362720AAA,IND362560AAA,0.0,0.0,0.0000,-1.0
90,trip-153816910069311424,IND122004AAA,IND122413AAE,2.0,0.0,0.5277,-1.0
164,trip-153705589682687518,IND206001AAA,IND000000ACB,0.0,0.0,0.0000,-1.0
224,trip-153781356401330282,IND560048AAB,IND560099AAB,0.0,0.0,0.0000,-1.0
236,trip-153746616495500586,IND127201AAA,IND124141AAA,1.0,0.0,1.1662,-1.0
261,trip-153689604975253520,IND560099AAB,IND560058AAB,0.0,0.0,0.0000,-1.0
281,trip-153860909786408355,IND384205AAA,IND384170AAA,0.0,0.0,0.0000,-1.0
298,trip-153807462781768214,IND683511AAA,IND000000ABA,0.0,0.0,0.4861,-1.0
325,trip-153775782037183132,IND413002AAA,IND501359AAE,2.0,0.0,0.4280,-1.0
450,trip-153790475017661884,IND400072AAB,IND421302AAG,0.0,0.0,0.0000,-1.0
465,trip-153674022097541190,IND400072AAB,IND421302AAG,0.0,0.0,0.0000,-1.0
617,trip-153714252401491359,IND781005AAA,IND781018AAB,0.0,0.0,0.0000,-1.0
824,trip-153740455519678193,IND624202AAA,IND625218AAA,0.0,0.0,0.0000,-1.0
827,trip-153801648339170824,IND605601AAA,IND607106AAA,0.0,0.0,0.0000,-1.0
850,trip-153801648339170824,IND606201AAC,IND605601AAA,0.0,0.0,0.0000,-1.0
954,trip-153789659881314008,IND400705AAA,IND421302AAH,0.0,0.0,0.0000,-1.0
972,trip-153721883745449045,IND571104AAA,IND577598AAB,0.0,0.0,0.0000,-1.0
1015,trip-153791084714708100,IND742223AAA,IND742226AAA,8.0,0.0,0.2113,-1.0
1047,trip-153857657012488227,IND591123AAC,IND587103AAB,3.0,0.0,0.1494,-1.0

In [26]:
df_clean = df.copy()

# already cleaned negative segment actual time earlier
df_clean = df_clean[df_clean["segment_actual_time"] >= 0].copy()

# drop impossible OSRM zero rows for modeling and analysis
df_clean = df_clean[df_clean["segment_osrm_time"] > 0].copy()

# drop negative factor rows if any remain
df_clean = df_clean[df_clean["segment_factor"] >= 0].copy()

print("After cleaning:", df_clean.shape)

After cleaning: (142502, 29)

In [27]:
df_clean.to_csv("../data/processed/delivery_data_clean.csv", index=False)